# This is a basic workflow to help you get started with Actions

name: GH Static Page Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build and Test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
        # more on checkout@v2 is here: https://github.com/actions/checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:ci
      - name: Test
        run: npm run test:ci
      
      - name: Raise version
        run: npm version patch

      # - name: Archive build
      #   if: success()
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: deploy_dist
      #     path: dist
                  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Download build
          uses: actions/download-artifact@v1
          with:
            name: deploy_dist
        # more on Deploying to Github Pages in documentation: https://github.com/JamesIves/github-pages-deploy-action
        - name: Deploy to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: deploy_dist/LotteryNumberGenerator
            TARGET_FOLDER: docs
